/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.drewhamlett.jsbeautify.ui;

import com.drewhamlett.jsbeautify.JSBeautifyOptions;
import org.openide.util.NbPreferences;

final class JSBeautifyPanel extends javax.swing.JPanel {

	private final JSBeautifyOptionsPanelController controller;

	JSBeautifyPanel( JSBeautifyOptionsPanelController controller ) {
		this.controller = controller;
		initComponents();
		// TODO listen to changes in form fields and call controller.changed()
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        useTabs = new javax.swing.JCheckBox();
        preserveNewLines = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(useTabs, org.openide.util.NbBundle.getMessage(JSBeautifyPanel.class, "JSBeautifyPanel.useTabs.text")); // NOI18N
        useTabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useTabsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(preserveNewLines, org.openide.util.NbBundle.getMessage(JSBeautifyPanel.class, "JSBeautifyPanel.preserveNewLines.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preserveNewLines)
                    .addComponent(useTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(useTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preserveNewLines)
                .addContainerGap(438, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void useTabsActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_useTabsActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_useTabsActionPerformed

	void load() {

		preserveNewLines.setSelected( JSBeautifyOptions.getInstance().getOption( "preserveNewLines", true ) );
		useTabs.setSelected( JSBeautifyOptions.getInstance().getOption( "useTabs", false ) );
	}

	void store() {

		JSBeautifyOptions.getInstance().setOption( "preserveNewLines", preserveNewLines.isSelected() );
		JSBeautifyOptions.getInstance().setOption( "useTabs", useTabs.isSelected() );
	}

	boolean valid() {
		// TODO check whether form is consistent and complete
		return true;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox preserveNewLines;
    private javax.swing.JCheckBox useTabs;
    // End of variables declaration//GEN-END:variables
}
